server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/searchengine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

    username: Warg
    password: engine

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
    drop-first: false

  output:
    ansi:
      enabled: ALWAYS

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru
      name: Svetlovka.ru
    - url: https://www.playback.ru
      name: PlayBack.Ru



