server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/searchengine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: Warg
    password: engine

  jpa:
    properties:
      hibernate:
        jdbc:
        batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: false
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: true

  output:
    ansi:
      enabled: ALWAYS

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: Svetlovka.ru
    - url: http://www.playback.ru/
      name: PlayBack.Ru
    - url: https://practicum.yandex.ru/
      name: Yandex.Practicum

connection-settings:
  settings:
  - userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
    referrer: http://www.google.com
  - userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
    referrer: http://www.bing.com
  - userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) YandexBrowser/21.9.0.1234.0 Chrome/93.0.4577.82 Safari/537.36
    referrer: http://www.yahoo.com
  - userAgent: Mozilla/5.0 (Linux; Android 10; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.62 Mobile Safari/537.36
    referrer: http://www.example.com
